name: Wake up Streamlit

on:
  schedule:
    # S'ex√©cute toutes les 4 heures (0h, 4h, 8h, 12h, 16h, 20h UTC)
    - cron: '0 */4 * * *'
  workflow_dispatch: # Permet de le lancer manuellement pour tester

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -I https://geopolitical-conflict-analysis-2bnirh6dz4y4cblvau7qc9.streamlit.app/
